version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      dockerfile: Dockerfile
      args:
        uid: ${UID}
    container_name: ${APP_NAME}
    restart: unless-stopped
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - ${APP_NAME}

  mysql:
    image: mysql:8
    container_name: ${APP_NAME}_mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
    networks:
      backend:
        aliases:
          - ${APP_NAME}_mysql-db

  redis:
    image: redis:6.0-alpine
    container_name: ${APP_NAME}_redis
    ports:
      - "6380:6379"
    restart: unless-stopped
    tty: true

  #PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_phpmyadmin
    ports:
      - "80:80"
    restart: unless-stopped
    tty: true
    # links:
    #   - database:db
    depends_on:
      - mysql
    networks:
      backend:
        aliases:
          - ${APP_NAME}_phpmyadmin

networks:
  backend:
    name: ${APP_NAME}-network